# Generated by Django 5.2 on 2025-04-26 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_serviceunit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculation',
            options={'get_latest_by': 'period', 'ordering': ['-period']},
        ),
        migrations.AlterField(
            model_name='service',
            name='units',
            field=models.ManyToManyField(blank=True, to='main.unit'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.unit'),
        ),
    ]
